# Generated by Django 4.2.3 on 2023-08-06 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BTC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='name')),
                ('price', models.FloatField(default=0, verbose_name='Currency')),
            ],
            options={
                'verbose_name': 'Coin',
                'verbose_name_plural': 'Crypto_currency',
                'ordering': ('name',),
            },
        ),
    ]
