# Generated by Django 4.2.3 on 2023-08-06 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_currency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='btc',
            name='time_crypto',
            field=models.CharField(default='time', max_length=40),
        ),
    ]
