# Generated by Django 4.2.3 on 2023-07-13 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_goods_alter_category_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Goods',
            new_name='Good',
        ),
    ]
