# Generated by Django 4.2.3 on 2023-07-14 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_rename_goods_good'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='country',
            field=models.CharField(default='країна', max_length=25, verbose_name='Країна виробник'),
        ),
        migrations.AlterField(
            model_name='good',
            name='price',
            field=models.FloatField(verbose_name='Ціна $'),
        ),
    ]
