# Generated by Django 4.2.3 on 2023-07-19 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_good_country_alter_good_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='catalog.category'),
            preserve_default=False,
        ),
    ]
