# Generated by Django 4.2.3 on 2023-08-04 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_category_options_alter_good_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='category',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='catalog.category'),
        ),
        migrations.AlterField(
            model_name='good',
            name='tags',
            field=models.ManyToManyField(default=True, related_name='goods_tag', to='catalog.tag'),
        ),
    ]
