# Generated by Django 4.2.3 on 2023-08-22 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_good_category_alter_good_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='tags',
            field=models.ManyToManyField(related_name='goods_tag', to='catalog.tag'),
        ),
    ]
