# Generated by Django 4.2.3 on 2023-09-22 13:25

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_category_level_category_lft_category_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='image'),
        ),
    ]
