# Generated by Django 4.2.3 on 2023-08-30 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Name')),
                ('price', models.FloatField(default=0.0, verbose_name='Price')),
                ('active', models.BooleanField(default=False, verbose_name='Active')),
                ('create', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Crate')),
                ('update', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Update')),
            ],
            options={
                'verbose_name': 'Транзакції',
                'verbose_name_plural': 'Транзакції',
                'ordering': ('id',),
            },
        ),
    ]
